services:

  # -----------------------
  # MinIO (stockage S3)
  # -----------------------
  minio:
    image: quay.io/minio/minio
    container_name: dl_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpass123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    networks:
      - data_lake_net

  # -----------------------
  # Generator
  # -----------------------
  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    container_name: generator
    depends_on:
      - minio
    environment:
      BRONZE_BUCKET: bronze
      AWS_ACCESS_KEY_ID: rootuser
      AWS_SECRET_ACCESS_KEY: rootpass123
      S3_URL: http://minio:9000
    networks:
      - data_lake_net

  # -----------------------
  # Cleaner
  # -----------------------
  cleaner:
    build:
      context: ./cleaner
      dockerfile: Dockerfile
    container_name: cleaner
    depends_on:
      - minio
      - generator
    environment:
      BRONZE_BUCKET: bronze
      SILVER_BUCKET: silver
      AWS_ACCESS_KEY_ID: rootuser
      AWS_SECRET_ACCESS_KEY: rootpass123
      S3_URL: http://minio:9000
    networks:
      - data_lake_net

  # -----------------------
  # Aggregator
  # -----------------------
  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    container_name: aggregator
    depends_on:
      - minio
      - cleaner
    environment:
      SILVER_BUCKET: silver
      GOLD_BUCKET: gold
      AWS_ACCESS_KEY_ID: rootuser
      AWS_SECRET_ACCESS_KEY: rootpass123
      S3_URL: http://minio:9000
    networks:
      - data_lake_net

networks:
  data_lake_net:
    driver: bridge
